OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Supplier
    Domain: supplier.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Hospital
    Domain: hospital.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1
  - Name: Patient
    Domain: patient.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1